### ISSUE TITLE
Health changing upon changing weapons 

### ISSUE THREAD

**Issue by JupiterYourHero** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#11]
Ill have an weapon and ill switch to a tool and my max health will decrease.

**Comment by TheXFactor117** [comment]
Known issue - I'll look to get it fixed soon. Likely related to #8.

Are there any specific steps to reproducing it (e.g. what are the two weapons you switch between and what are the attributes on it if applicable [additionally, do you have any armor/baubles equipped as well?])

**Comment by TheXFactor117** [comment]
Should be fixed in 0.6.1.1 - re-open this if it still occurs.
