### ISSUE TITLE
Server Problem

### ISSUE THREAD

**Issue by Thuah** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#13]
My Friend created a server and we added the mod in but it does not work at all. The Gui and everything is there but we don't get exp. I also noticed once you die , your class resets and you have to pick again. We tested it in single player and it works fine . But not on our forge server. Any suggestions

**Comment by TheXFactor117** [comment]
I'll look into - which version of LSC are you using?

0.6.1.1 could've potentially broke it, but I know some guys in the Discord have been running on a server without any problems.

**Comment by Thuah** [comment]
We are using Loot Slash Conquer-1.12.2-0.6.1.0-alpha. Which version are they using . I didn't see another version for LSC on the website.

**Comment by TheXFactor117** [comment]
I'll check up with some guys who are running servers - they haven't had any issues like that but it could've gotten overlooked perhaps.

**Comment by Thuah** [comment]
sweet that that will be great ! We are going to experiment with the other versions to see if we have the same problem. Will let you know which one works.

**Comment by TheXFactor117** [comment]
They are probably using 0.6.1.0 as well - I just released 0.6.1.1 a few minutes ago which fixed a few server related crashes. In the meantime, you can try using 0.6.1.1, though I doubt it would fix issues if you had them using 0.6.1.1.

I might need some more information later - I'll let you know if I do. I'm assuming the issues are happening to everyone on the server?

**Comment by Thuah** [comment]
correct they are. We just tried 0.6.1.1, didn't work as expected. Will try using the 0.6.1.0

**Comment by TheXFactor117** [comment]
I'll test it when I get a chance as well.

**Comment by Thuah** [comment]
oh my bad thats the one that we had originally. We going to test 0.6.0.2 going down to 0.6.0.0.

**Comment by TheXFactor117** [comment]
If you're experiencing issues with 0.6.1.0, it's most likely the same for versions below it.

**Comment by TheXFactor117** [comment]
So I just tested this in my dev environment server using 0.6.1.1 - I was able to kill monsters and gain experience and when I died, I kept my experience/level/class.

Though, sometimes issues don't show up in my dev environment and are only present when the mod is built.

![2018-07-12_17 04 15](https://user-images.githubusercontent.com/6678711/42659322-e2abe242-85f5-11e8-9857-bbe0b0b704bf.png)

I'll test it using the built version and see if the error shows up.

**Comment by cdcp998** [comment]
In a sponge environment, if you die or change the map, it may cause the data to disappear temporarily, but you may recover if you hit a monster or upgrade one level.

**Comment by cdcp998** [comment]
![or d4 mhqfby _piu p8f](https://user-images.githubusercontent.com/1726165/42660447-d25faf64-865d-11e8-9321-af7580f4d487.png)
![2r d_5mft3p4qzww f7_rc](https://user-images.githubusercontent.com/1726165/42660452-d4516312-865d-11e8-8b64-5eb59c8a0fc3.png)
If you kill a monster, it is normal
![fck70edchj st_6qxi oas](https://user-images.githubusercontent.com/1726165/42660536-1189dac0-865e-11e8-9a97-4368121acdde.png)

**Comment by TheXFactor117** [comment]
I'm assuming the second picture is after death?

I just tested this on a test server and was able to gain experience, die, and maintain everything I had. Weapons got stats rolled properly and enemies were given correct levels/tiers. What version were those screenshots taken from @Thuah ? I'm using 0.6.1.1 in my testing too.

**Comment by Thuah** [comment]
the first picture is from 0.6.0.2 second picture was from 0.6.1.1

**Comment by cdcp998** [comment]
No, my server。

**Comment by TheXFactor117** [comment]
@Thuah I just set up a brand new server/world using 0.6.1.1 and was able to do everything fine. There's definitely an issue somewhere considering enemies/loot isn't working properly. I know this may be a hassle but could create a new world/server (doesn't have to remove the original) and test using a clean state. Perhaps something broke/ended up bugging out somehow (either between version changes or something else). Use 0.6.1.1 too, if you don't mind.

**Comment by Thuah** [comment]
Yeah we just created a fresh one with that version (0.6.1.1). Still the same thing, **no changes**

**Comment by Thuah** [comment]
ITS WORKING ! Woooo . We are not sure how it fixed. We just restarted everything and it worked .

**Comment by TheXFactor117** [comment]
Huh...well there we go :). If you run into any other issues, just create a new issue.
