### ISSUE TITLE
Suggestions add more language settings

### ISSUE THREAD

**Issue by cdcp998** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#14]
I submitted to the zh_CN.lang
Want more language settings
Thank you

**Comment by TheXFactor117** [comment]
How/Where did you submit the lang file?

**Comment by cdcp998** [comment]
git，However, I may not use GIT.
I will send it to you now.
[zh_CN.TXT](https://github.com/TheXFactor117/Loot-Slash-Conquer/files/2190325/zh_CN.TXT)

**Comment by TheXFactor117** [comment]
Added.
