### ISSUE TITLE
Suggestions and bugs

### ISSUE THREAD

**Issue by JupiterYourHero** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#15]
Have health of enemy decide amount of exp give to the player.
Allow Item repair 
Compatibility with Quality Tools? (idk)
Make Golems more aggressive 
_______________________
Barbarion and other mobs hitting through thin walls

**Comment by TheXFactor117** [comment]
I'll mark these down internally :)

Experience goes through a pretty complex algorithm which uses level, tier, and rarity to determine the experience dropped (which is indirectly using health to decide experience).

Item repairing is an issue I noticed - will look into in the future.

Compatibility between additional mods is a future thing. I'll mark down Quality Tools and look at it when compatibility does become a priority.

I can certainly buff Golems :)

I noticed the issue with that - no idea how it happens considering it's using vanilla AI. Might be out of my realm to fix.
