### ISSUE TITLE
High Area Level's cause the game to freeze up

### ISSUE THREAD

**Issue by cdcp998** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#16]
I also found a problem,When you create a map in Sponge, the new map will not refresh Tower Dungeons.

If the damage is higher than 5000000, it will cause the game to be stuck.

**Comment by TheXFactor117** [comment]
What do you mean by Tower's not refreshing?

And are you getting damage values that high because you are going really far away from spawn (into high Area Levels?)

**Comment by cdcp998** [comment]
![zuzvp9rhe1d33xjr5amw 9n](https://user-images.githubusercontent.com/1726165/42661437-c19bc6c4-8660-11e8-80af-90e5dd61a543.png)


YES.I entered the 120-level area, the monster HP is tens of millions

![gc ewo u3hq i 7_ 1zzq](https://user-images.githubusercontent.com/1726165/42661596-4331d020-8661-11e8-93ef-8bf95a290658.png)

**Comment by TheXFactor117** [comment]
Yeah, that could break things due to Java limitations. The mod isn't designed to scale that far - I need to add a level cap to prevent this kind of stuff.

**Comment by cdcp998** [comment]
In fact, this is a performance bug.If the attack is higher, there will be blood loss effects after the attack, 1HP will be one. If it is 5000HP, it will be 5000 blood loss effects.

**Comment by TheXFactor117** [comment]
Blood effects as in the particles spawning?

**Comment by cdcp998** [comment]
YES。

**Comment by TheXFactor117** [comment]
Are you using a custom resource pack?

The particles should have been removed.

**Comment by cdcp998** [comment]
yes.

**Comment by TheXFactor117** [comment]
Ah well there's that. Can't do anything about the particles.

**Comment by cdcp998** [comment]
Thank you。understood

**Comment by MokahTGS** [comment]
How configurable is this kind of stuff?  With mod packs that don't rely on the overworld will we get massively overpowered mobs in other dimensions?

**Comment by TheXFactor117** [comment]
Fixed in 0.6.2.0
