### ISSUE TITLE
Mob ranks break down on the user interface after level 5

### ISSUE THREAD

**Issue by DuNamarSundavar** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#23]
I have no idea if this occurs on the mod-side with algorithms as well, but if a mob is higher than level 5, its nameplate will display (default Level X), X being the mob's level.

**Comment by DuNamarSundavar** [comment]
Every mob in vanilla and the ones added by LSC is affected. I can't tell you about any other mobs added by mods, as I have none installed, having created an environment specifically for playtesting the mod. I can say for certainty that every vanilla and LSC mob, though, is affected by the level 6+ (default) nameplate bug.

**Comment by TheXFactor117** [comment]
Figured it out. Typo by me...should be fixed in the next version (0.6.1.3)
