### ISSUE TITLE
UniverseGuard under spong will result in unlimited attribute points

### ISSUE THREAD

**Issue by cdcp998** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#25]
![w7 c0 rrfk4 m 89 ymo d](https://user-images.githubusercontent.com/1726165/42766602-77c2253a-894d-11e8-9ece-8ef7be37b80f.png)

**Comment by TheXFactor117** [comment]
Can you describe exactly what is causing you to have unlimited skill points?

**Comment by cdcp998** [comment]
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard
It may be caused by this plugin.

**Comment by TheXFactor117** [comment]
I don't see why it would be affected by a plugin.

**Comment by cdcp998** [comment]
Maybe you need to set up a spong try. Sorry

**Comment by mimiceolo** [comment]
I think you got problem with integer when attribute point over 2,147,483,647
