### ISSUE TITLE
Only one player at a time has the mod work at a time on the server (BUG)

### ISSUE THREAD

**Issue by isaacDhoward** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#27]
When me and my friend are playing on our server and are both logged on, only one person has mana and health regen and stat bosoting items work. But once the player who doesnt have any of that working leaves and comesback the original player whos mana health regen and boosts stop working.

**Comment by TheXFactor117** [comment]
I’ll look into it - I think I know what’s causing the issue.

**Comment by isaacDhoward** [comment]
thank you so much have a wonderful day

**Comment by cyberpwnn** [comment]
So..... @TheXFactor117 hows it going? Mind if you fix it or at least point out where it's happening?

**Comment by TheXFactor117** [comment]
Will be fixed in versions after 0.6.2.0.
