### ISSUE TITLE
Console errors- thexfactor117.lsc.loot.generation.ItemGeneratorHelper.setAttributeModifiers

### ISSUE THREAD

**Issue by ProsperCraft** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#28]
https://gist.github.com/ProsperCraft/0dc523c3efaa9e222f9c71445b46d9e4

Loot Slash Conquer-1.12.2-0.6.1.2-alpha

Modpack - https://minecraft.curseforge.com/projects/ancient-towncraft

Scroll to the bottom or search for the error above.

**Comment by TheXFactor117** [comment]
I'll look into it - could possibly be some kind of incompatibility with Wizardry but I'll check it out and see what's going on.

**Comment by MokahTGS** [comment]
It might be an incompatibility with Loot Bags and the Loot Bag auto opener.

Our crash log: https://pastebin.com/UEDgWgri

Here's our setup:
Forge 2756
LCS 1.12.2-0.6.1.2-alpha

Full mod list: https://pastebin.com/gB27AbEi

**Comment by ProsperCraft** [comment]
We don't have loot bags, and we don't' have auto opener.

**Comment by MokahTGS** [comment]
You misunderstand:  I'm talking about an incompatibility with the Loot Bags mod that items from your mod are getting generated out of.  Loot Bags has an auto opener for their bags.  Something is happening when those loot bags roll one of your items from the loot table.

Loot Bags mod: https://minecraft.curseforge.com/projects/lootbags

**Comment by MokahTGS** [comment]
Yes, but the errors are from the same thing: thexfactor117.lsc.loot.generation.ItemGeneratorHelper.setAttributeModifiers

So instead of creating more issues, perhaps we work together and find a common thread causing the issues.

**Comment by TheXFactor117** [comment]
If this is still an issue let me know.
