### ISSUE TITLE
error names on loot inside chests.

### ISSUE THREAD

**Issue by mattrix444** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#3]
hi i noticed the loot i get out of chests only have error in the names.  "error sash" and "error ring" they have %stats but nothing else.

**Comment by TheXFactor117** [comment]
Yes, I am aware of this issue. I recently re-worked some internal parts of the mod which broke certain name generation features. It'll be fixed very soon.

**Comment by mattrix444** [comment]
ah ok no worries :) still loving exploring the new content. brilliantly made mod so far. shall i close this?

**Comment by TheXFactor117** [comment]
Let's keep it open till the errors get fixed :)

**Comment by mattrix444** [comment]
ok cool. do you have a discord? it would be easier to chat about stuff other than issues i think.

**Comment by TheXFactor117** [comment]
[Yes, just click this link.](https://discord.gg/qDtkjke)

**Comment by TheXFactor117** [comment]
This will be fixed in 0.6.0.1.
