### ISSUE TITLE
Craft issue with reliquary

### ISSUE THREAD

**Issue by JupiterYourHero** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#30]
https://gyazo.com/09bc72eb3bea09bb03c7ebf3fef3b70e

**Comment by TheXFactor117** [comment]
Sorry for taking so long but I'll look into this at a later date - compatibility issues aren't at the top of my priority list right now.

**Comment by TheXFactor117** [comment]
I don't think this is an issue with LSC.
