### ISSUE TITLE
Getting this crash error while testing my modpack

### ISSUE THREAD

**Issue by Davoleo** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#32]
MC: 1.12.2
Loot-Slash-Conquer: 0.6.1.2 - alpha
Forge: 2739

crash report: https://paste.dimdev.org/ejerolamif.mccrash

**Comment by TheXFactor117** [comment]
I'll look into it - looks related to some of these other issues so I'm going to close this for now.
