### ISSUE TITLE
Mob Farm Crash

### ISSUE THREAD

**Issue by ghost** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#33]
Testing a custom modpack and I have an RFTools spawner setup to produce blazes and a shield around it to kill them with shield damage. When I changed the shield to do damage as a player, the pack consistently crashes. When I changed the damage type back to normal, didn't seem to be an issue. 

Crash report: https://pastebin.com/XXnSNK2i

Version: Loot Slash Conquer-1.12.2-0.6.1.2-alpha

**Comment by TheXFactor117** [comment]
I can see where the issue is coming from, I'll see what I can do.

**Comment by TheXFactor117** [comment]
This should be fixed in versions after 0.6.2.0 - open a new issue if it's not working properly.
