### ISSUE TITLE
Mod Compatibility - Future Plans for Modpacks

### ISSUE THREAD

**Issue by MokahTGS** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#36]
I'm in the process of putting together a magical themed mod pack that does a lot of custom stuff for dimensional hopping.  I was wondering what your plans were for mod integration as there are several mods that add mana and spell casting.  Also, will you be adding configuration options for spawning of structures?  I'm very interested in your bosses and the dungeons that they spawn, but would very much want to be able to control how and where they spawn.

In my case, the overworld is not normal, and is the space profile from Lost Cities which plays havoc with mods that do overworld generation.

At any rate, this mod looks awesome and I'll be keeping an eye on it and testing out whatever you come up with.

**Comment by TheXFactor117** [comment]
I'll look to add configuration options and compatibility in the future - for now I'm focusing on stabilizing the mod and getting it in a somewhat playable state.
