### ISSUE TITLE
Chained attack causing looping crash

### ISSUE THREAD

**Issue by qchronod** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#38]
I picked up a sword that had a +8 Chained attribute on it, and the couple of times when I tried to use it the entire server crashes (after it generates an enormous crash log)

https://gist.github.com/qchronod/4db937341436be06ea11df752512f944

Is there a way to disable certain attributes?

**Comment by MokahTGS** [comment]
We are getting a similar crash happening but it's in a SP hosted LAN environment.  It doesn't crash out but generated crash logs and freezes up the hosting system.  Definitely a problem.

Crash logs:
https://pastebin.com/UEDgWgri
https://pastebin.com/758QPwYJ

Here's our setup: 
Forge 2756
LCS 1.12.2-0.6.1.2-alpha

Full mod list: https://pastebin.com/gB27AbEi

**Comment by esabangan** [comment]
Same here everytime i use weapon with chained attributes my game is crashing in sp mode

**Comment by TheXFactor117** [comment]
Related to other issues - check them out instead.
