### ISSUE TITLE
Strength Configuration - OP?

### ISSUE THREAD

**Issue by MokahTGS** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#39]
I've been testing out the mod, and so far, it's really great.  The only major issue, is it seems to be pretty OP when you have the area leveling turned off.  I don't know if there is something that could be done about that, but I tried adjusting the configs and didn't find anything that controls Strength.  If I continually buff strength, I can one shot a stage 3 dragon from Ice and Fire.

Is the balance mechanic dependent on areas increasing in level?

**Comment by TheXFactor117** [comment]
I'll look into balancing once I can get the mod stabilized more.

**Comment by TheXFactor117** [comment]
The problem is area leveling - with it disabled, enemies aren't going to scale up so you're going to be absurdly powerful. It is a balancing issue, but it will get better over time.
