### ISSUE TITLE
Class and level revert to nothing and all skill points lost on death, or maybe exiting mod-added dimension?

### ISSUE THREAD

**Issue by AzureMonument** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#43]
I do not know if this is because of one of my other mods having bad compatibility (might be corpse complex), but in short, I was fighting a mass of mobs in the twilight forest on my save and had the unfortunate matter to die- which was my first death with this mod.
When I respawned I decided the twilight forest was a bit over my level (everything was level 16-20 while I was a measly level 6.) So I instantly exited, however upon exiting I noticed I had a little notification telling me some of the weapons and armor I was wielding was too high of a level. 
I didn't notice whether or not it was directly after my death in respawn in the twilight forest, or if it was after I exited. However all my stat points and level was reset, and even my class in the info screen was showing up as null. something or other. (my memory is not the best)
Nothing was popping up for me to reselect the class either.
Thank you for your time, if there is more you need to know please contact me.

**Comment by TheXFactor117** [comment]
I think I know what the problem with this is as well, I'll look into it.

**Comment by TheXFactor117** [comment]
Should be fixed in 0.6.2.0. There's a chance it's still not working for modded dimensions, but open a new issue if that's still the case.
