### ISSUE TITLE
Server glitch 

### ISSUE THREAD

**Issue by Neekos123** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#48]
While playing on my modded server I ran into a problem, using some weapons like doomshadow causes the server to freeze, it doesnt crash or create a crash reports, instead the console goes red infnitely. I had it also with other legendary weapon, not sure what stats it had, im using the newest forge and newest LSC. Also it occurs only when attacking hostile enemies. 
![sdfasdfasdfas](https://user-images.githubusercontent.com/49588589/56160171-c4b6fa00-5fc6-11e9-8c0e-5a251303facf.PNG)

**Comment by TheXFactor117** [comment]
This should be fixed in 0.6.2.0.
