### ISSUE TITLE
Crash after logged into world

### ISSUE THREAD

**Issue by Lordbaane** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#49]
https://paste.dimdev.org/akuriqopip.mccrash

**Comment by TheXFactor117** [comment]
I'm going to need some more information on what exactly you were doing at the time.

**Comment by Lordbaane** [comment]
Just trying to get into a chest or on a separate attempt, inside a chest when it crashed.

**Comment by TheXFactor117** [comment]
Looks like a generation issue. An item got a rarity value that shouldn't be possible to get. I'm not too sure how it got a number like that but if you can replicate the problem that might help me fix it. In the meantime to stop it from crashing you're going to have remove the bugged item somehow.

**Comment by Lordbaane** [comment]
I'll see what I can do.

**Comment by Lordbaane** [comment]
Appears to be a chain helmet, as soon as I mouse to it the game crashes, it came from a drop from one of the monsters in a Rogue Dungeon. Hope this helps.

**Comment by Lordbaane** [comment]
https://paste.dimdev.org/ubamadugol.mccrash

**Comment by TheXFactor117** [comment]
Yes that should help - I'll look into in a moment.

**Comment by Lordbaane** [comment]
Yep, it seems to be some conflict, tried to add enchantments on the anvil and crashed. Maybe a conflict with enhanced armaments? It gives it a rarity and maybe that is causing the issue?

**Comment by TheXFactor117** [comment]
Yeah that's the issue. The "author" of that mod is using my exact code. Take it up with him, not my issue.
