### ISSUE TITLE
I'm not getting xp!

### ISSUE THREAD

**Issue by jusah123** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#67]
Everything in the mod is working perfectly, except the XP and leveling. I've been playing for 3 days now, going through dungeons, getting loot. But not a SINGLE piece of experience has been gained. I check my class information screen and nothing changes. I picked my class and everything, so I'm a little confused. It just stays at 0/261, level 1.

Any help would be appreciated!

**Comment by Rensik** [comment]
You can only gain XP from Vanilla or LSC mobs right now. The fix is in dev and will be available next release. Any mods that change vanilla mobs could cause that no XP issue. Try removing any of those first.

**Comment by jusah123** [comment]
I see no mods except mo'bends (which I tried) that changes vanilla mobs. I'll just wait for the next update, got a few games to play first anyways. Thanks!
