### ISSUE TITLE
Rings and Weapons not working together

### ISSUE THREAD

**Issue by pinwazkev** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#8]
When im wearing a ring and holding air its active, but when I hold a sword while wearing a ring it removes rings buffs.

**Comment by TheXFactor117** [comment]
I'll look into it - I think I know what the issue is.

**Comment by TheXFactor117** [comment]
Should be fixed in 0.6.1.1 - re-open this if the issue still occurs.
